### ISSUE TITLE
无法安装，提示七牛phpsdk的主版本不存在

### ISSUE THREAD

**Issue by jinqibu** [stevenyangecho/laravel-u-editor#1]
> Loading composer repositories with package information 
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

>  Problem 1
 >  - stevenyangecho/laravel-u-editor v1.1.1 requires qiniu/php-sdk dev-master -> no matching package found.
>  - stevenyangecho/laravel-u-editor v1.1.0 requires qiniu/php-sdk dev-master -> no matching package found.
  >  - Installation request for stevenyangecho/laravel-u-editor ~1.1 -> satisfiable by stevenyangecho/laravel-u-editor[v1.1.0, v1.1.1].

> Potential causes:
 > - A typo in the package name
 > - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

>  Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by stevenyangecho** [comment]
七牛官方的 SDK 7.x版本 没有发布到 composer...
只有暂时 先 在 项目composer.json 里面 手动添加require
 "qiniu/php-sdk": "dev-master"
试试

**Comment by stevenyangecho** [comment]
对了,项目里面 composer.json 这个最小安装是不是dev? 改成dev应该也可以的
 "minimum-stability": "dev",

**Comment by jinqibu** [comment]
还是不行

**Comment by jinqibu** [comment]
一定需要依赖qiniu 7以上版本吗？能否改为6，不然无法安装

**Comment by stevenyangecho** [comment]
把你 composer.json 发过来看看呢,我这边测试ok的

必须是7.x版本的

**Comment by jinqibu** [comment]
因为我不想让"minimum-stability": "dev"，还是想用稳定版本的

修改了之后可以安装了。然后核心更新了一大堆。哈哈

谢谢您的分享。

**Comment by jinqibu** [comment]
- Removing qiniu/php-sdk (v6.1.13)
  - Installing qiniu/php-sdk (dev-master f67af3f)
    Downloading: connection...    Downloading: 0%
    Downloading: 40%
    Downloading: 75%
    Downloading: 100%

  - Installing stevenyangecho/laravel-u-editor (v1.1.1)
    Downloading: connection...    Downloading: 0%
    Downloading: 5%
    Downloading: 10%
    Downloading: 15%
    Downloading: 20%
    Downloading: 25%
    Downloading: 30%
    Downloading: 35%
    Downloading: 40%
    Downloading: 45%
    Downloading: 50%
    Downloading: 55%
    Downloading: 60%
    Downloading: 65%
    Downloading: 70%
    Downloading: 75%
    Downloading: 80%
    Downloading: 85%
    Downloading: 90%
    Downloading: 95%
    Downloading: 100%
    Downloading: 100%

**Comment by stevenyangecho** [comment]
我已经提交 七牛官方了,请他发布 7.x 到composer,到时候我会第一时间更新 的~
