### ISSUE TITLE
关于加git的问题

### ISSUE THREAD

**Issue by gclinux** [stevenyangecho/laravel-u-editor#16]
因为是用composer装的,在laravel里面的ueditor不知道加不到项目里面好,如果只加几个config文件,通过服务器git来更新代码,就需要登录服务器来编辑,背离了laravel的原则.

**Comment by stevenyangecho** [comment]
没太明白什么意思,vendor 目录,看项目部署,加不加都可以.
需要什么来登录服务器来编辑,也不明白意思
