### ISSUE TITLE
上传不能正常使用

### ISSUE THREAD

**Issue by QinFeiFei** [stevenyangecho/laravel-u-editor#18]
Laravel 版本为5.2，浏览器控制器报 Get server config http error. 路由也按说明修改，始终无法正常使用

**Comment by QinFeiFei** [comment]
还有，php artisan vendor:publish    最后一步做完，在config 目录下生成的配置文件名是 UEditorUpload.php，并不是 laravel-u-editor.php

**Comment by QinFeiFei** [comment]
问题解决了。是middleware的原因。现在有个新的问题，如果前台后台都使用的话，middleware怎么写。

**Comment by stevenyangecho** [comment]
现代程序大多是前后台统一认证资源的,如果是分开的认证资源,
一种方法是 可以临时写一个middleware,这个middleware同时兼容两种认证,比如先判断前台,为false,再判断一次后台即可
