### ISSUE TITLE
配置了本地环境和七牛但是上传图片不成功

### ISSUE THREAD

**Issue by jinqibu** [stevenyangecho/laravel-u-editor#2]
{"state":"can't find the uploaded file","url":null,"title":null,"original":null,"type":null,"size":null}

**Comment by jinqibu** [comment]
/* 上传图片配置项 */
        'upload' => [
            "imageActionName"         => "uploadimage", /* 执行上传图片的action名称 */
            "imageFieldName"          => "upfile", /* 提交的图片表单名称 */
            "imageMaxSize"            => 2048000, /* 上传大小限制，单位B */
            "imageAllowFiles"         => [".png", ".jpg", ".jpeg", ".gif", ".bmp"], /* 上传图片格式显示 */
            "imageCompressEnable"     => true, /* 是否压缩图片,默认是true */
            "imageCompressBorder"     => 1600, /* 图片压缩最长边限制 */
            "imageInsertAlign"        => "none", /* 插入的图片浮动方式 */
            "imageUrlPrefix"          => "", /* 图片访问路径前缀 */
            "imagePathFormat"         => "/uploads/ueditor/php/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}", /* 上传保存路径,可以自定义保存路径和文件名格式 */

**Comment by jinqibu** [comment]
uploads目录及子目录权限已经改为可写

**Comment by stevenyangecho** [comment]
'core' => [
        'route' => [
            'middleware' => 'auth',
        ],
        'mode'=>'local',//上传方式,local 为本地   qiniu 为七牛
        //七牛配置,若mode='qiniu',以下为必填.
        'qiniu'=>[
            'accessKey'=>'',
            'secretKey'=>'',
            'bucket'=>'',
            'url'=>'http://xxx.clouddn.com',//七牛分配的CDN域名,注意带上http://
        ]
    ],

关键是包的配置,权限没问题的话,检查 中间件 'middleware' => 'auth',
如果不了解,可以直接 设置 'middleware' => '',

**Comment by jinqibu** [comment]
auth检测已经通过了，'Stevenyangecho\UEditor\UEditorServiceProvider',已经配置

**Comment by jinqibu** [comment]
通过debug，发现下面这段代码抛出了异常

 if(config('UEditorUpload.core.mode')=='local'){
            try {
                $this->file->move(dirname($this->filePath), $this->fileName);

                $this->stateInfo = $this->stateMap[0];

            } catch (FileException $exception) {
                $this->stateInfo = $this->getStateInfo("ERROR_WRITE_CONTENT");
                return false;
            }

        }

**Comment by jinqibu** [comment]
使用firebug可以看到post里面有数据，但是到服务器的Controller里面没有file

**Comment by stevenyangecho** [comment]
看样子,似乎应该是目录权限问题啊
你直接 打印 dirname($this->filePath), $this->fileName 这两个变量,就可以调试看到底哪里出错了

**Comment by jinqibu** [comment]
为空

**Comment by jinqibu** [comment]
我在本地搭建的服务器，使用了虚拟目录，映射到了xxx.xx的模拟域名的主机，不知道有没有影响

**Comment by jinqibu** [comment]
imageUrlPrefix配置项的作用是什么呢？

**Comment by stevenyangecho** [comment]
php 能上传 文件,就没问题,建议检查下php 本身的上传设置
upload 里面的配置是ueditor 官方的,可以暂时都不用管

**Comment by jinqibu** [comment]
经过301重定向之后，调试得出请求中没有$_FILES

**Comment by jinqibu** [comment]
调试过程中发现Controller的构造方法中都没有$_FILES

**Comment by jinqibu** [comment]
会不会是因为csrf

**Comment by stevenyangecho** [comment]
你提醒我了,下个版本得修复

不过 打开了csrf,laravel 会
throw   Illuminate \ Session \ TokenMismatchException  

应该还不会走到上传那去的

**Comment by stevenyangecho** [comment]
突然发现,ueditor 在低版本浏览器 会自动使用其他的上传方式...或许是这个问题?
你用的是什么浏览器呢?

**Comment by luotmtool** [comment]
火狐 http://localhost/laravel-u-editor/server/?action=uploadimage&encode=utf-8&_token=mxROUndKO1daPt2sXRRqZWjX3UlzueE1pzcClODE  500错误

**Comment by stevenyangecho** [comment]
打开 app.debug
火狐打开 firebug,看下具体的错误信息

**Comment by luotmtool** [comment]
我改了
        $file = $this->request->file($this->fileField);

        if (!$file) {
            $this->stateInfo = $this->getStateInfo("ERROR_FILE_NOT_FOUND");
            return false;
        }
改成

        $file = $this->request->file($this->fileField);

        if (empty($file)) {
            $this->stateInfo = $this->getStateInfo("ERROR_FILE_NOT_FOUND");
            return false;
        }
就可以了，不知道是否有其他影响

**Comment by luotmtool** [comment]
原本的错误 ：Object of class Symfony\Component\HttpFoundation\File\UploadedFile could not be converted to boolean

**Comment by stevenyangecho** [comment]
谢谢,欢迎提交PR~~~

**Comment by queenmimi** [comment]
cant upload local image file too

**Comment by stevenyangecho** [comment]
注意 csrf 的配置

**Comment by yinchuandong** [comment]
![image](https://cloud.githubusercontent.com/assets/3993196/9148553/d4579850-3db2-11e5-9303-46b64f67d73a.png)

您好，我想请问下为什么会产生301重定向，我现在也是重定向之后获取不到$_FILE

**Comment by partychen** [comment]
change serverUrl: "/laravel-u-editor/server/" to serverUrl: "/laravel-u-editor/server" will avoid 301.
