### ISSUE TITLE
Laravel 5.3 RouteServiceProvider boot 方法没有参数

### ISSUE THREAD

**Issue by MusaZhou** [stevenyangecho/laravel-u-editor#20]
当我们在laravel 5.3里去跑 artisan vendor:publish时会报:
Declaration of Stevenyangecho\UEditor\UEditorServiceProvider::boot() should be compatible with Illuminate\Foundation\Support\Providers\RouteServiceProvider::boot()
原因是新版的RouteServiceProvide::boot()没有参数了，我们需要将UEditorSeriveProider::boot()里的$route参数删掉

原函数
public function boot($route){
     parent::boot($route);
     ........................
     ........................
}

新函数
public function boot(){
     parent::boot();
     ........................
     ........................
}

**Comment by stevenyangecho** [comment]
1.4.0已支持
