### ISSUE TITLE
安装1.4版本，后台需要怎么配置

### ISSUE THREAD

**Issue by DoubleYing** [stevenyangecho/laravel-u-editor#24]
后端需要怎么配置，才能实现上传图片的功能

**Comment by engty** [comment]
同问，php7.0下搞了半天，一上传就提示“上传失败”，后来发现切换回php5.5又正常了。

**Comment by DoubleYing** [comment]
那你在php5.5下面是怎么配置的呢？

**Comment by stevenyangecho** [comment]
出现错误,
1.chrome 看js请求错误信息,
2.看php错误日志
