### ISSUE TITLE
如何解决：后台配置项返回格式出错，上传功能将不能正常使用

### ISSUE THREAD

**Issue by mvp-xuan** [stevenyangecho/laravel-u-editor#28]
ueditor.all.min.js:9 后台配置项返回格式出错，上传功能将不能正常使用！
showErrorMsg @ ueditor.all.min.js:9
onsuccess @ ueditor.all.min.js:9
d.onreadystatechange @ ueditor.all.min.js:9

laravel5.1和ueditor1.4
已经尝试过：
1、注释middleware验证、
2、修改//替换随机字符串$randNum = rand(1, 100000000) . rand(1, 100000000);、
3、没有找到时区修改、
4、ueditor.config.js中的var URL = "/laravel-u-editor/";、
无奈了。。

**Comment by stevenyangecho** [comment]
4、ueditor.config.js中的 
 , serverUrl: "/laravel-u-editor-server/server"

1.4.1 版本已修复
