### ISSUE TITLE
找不到controller.php文件

### ISSUE THREAD

**Issue by xlkit456852** [stevenyangecho/laravel-u-editor#29]
按照配置配好后，JS报错：
ueditor.all.min.js:9 GET http://localhost/jd/public/laravel-u-editor/php/controller.php?action=config&&noCache=1484621620061 404 (Not Found)
找过public/laravel-u-editor目录下，的确没有php/controller.php文件？

**Comment by jiangguoliang** [comment]
请问您解决了吗？可否分享一下解决办法，谢谢

**Comment by jiangguoliang** [comment]
解决办法：
1、找到public/laravel-u-editor/ueditor.config.js文件
2、修改如下：
` // 服务器统一请求接口路径
        , serverUrl: "/laravel-u-editor-server/server"`

我怀疑楼主忘记修改了，希望楼主修改一下这个bug

**Comment by stevenyangecho** [comment]
@jiangguoliang  真搞忘了...谢谢,1.4.1已修复

**Comment by szwss** [comment]
1.4.1很棒谢谢
