### ISSUE TITLE
N个bug，这插件还能用吗？

### ISSUE THREAD

**Issue by szwss** [stevenyangecho/laravel-u-editor#30]
1：发布配置命令php artisan vendor:publish，一个文件没发布，结果看源码一个个手动复制过来
2：@include('UEditor::head');这个是放在blade里吧，提示出错No hint path defined for [UEditor]，又手动改成@include('vendor.UEditor.head')，可以引入head了
3：include head后又报错Undefined variable: UeditorLangFile，立马崩溃

不想再搞下去了，无底洞

**Comment by stevenyangecho** [comment]
按照说明来,估计是你在config/app.php 没有编辑
