### ISSUE TITLE
如何正确配置后台配置项

### ISSUE THREAD

**Issue by shjchen** [stevenyangecho/laravel-u-editor#4]
GET http://www.example.com/laravel-u-editor/server/?action=config&&noCache=1429803138387 500 (Internal Server Error)

ueditor.all.min.js:124 请求后台配置项http错误，上传功能将不能正常使用！ueditor.all.min.js:124 dueditor.all.min.js:125 UE.Editor.loadServerConfig.UE.ajax.request.onerrorueditor.all.min.js:127 UE.ajax.e.onreadystatechange

以上为报错内容。
目前在个人使用中，不需要使用到后台的配置错误，我只需要使用到很简单的文本、列表等排版功能。
 var ue = UE.getEditor('container',{
        toolbars: [
            ['fullscreen', 'undo','|', 'redo', 'bold', 'italic', 'underline','|', 'justifyleft', 'justifycenter', 'justifyright',
                '|','insertorderedlist', 'insertunorderedlist','indent','horizontal']
        ],
        //关闭字数统计
        wordCount:false,
        pasteplain:true,
        //关闭elementPath
        elementPathEnabled:false,
        //默认的编辑区域高度
        initialFrameHeight:200
    });
编辑器能够正确使用，但是会报前面的错误。
我做过如下尝试：
建立laravel-u-editor/server 路由，方法里写简单的内容，但是仍然会提示这种js的错误。

请教该如何解决这个问题，谢谢！

**Comment by stevenyangecho** [comment]
请详细阅读readme
估计是没有运行
php artisan vendor:publish

**Comment by stevenyangecho** [comment]
另外请注意 middleware 的配置
