### ISSUE TITLE
laravel5.3 composer安装的ueditor,后台配置项返回格式出错,上传功能不能用。

### ISSUE THREAD

**Issue by st-titan** [stevenyangecho/laravel-u-editor#40]
后台配置项返回格式出错，上传功能将不能正常使用！showErrorMsg @ ueditor.all.min.js:9onsuccess @ ueditor.all.min.js:9d.onreadystatechange @ ueditor.all.min.js:9
ueditor.all.min.js:9
 XHR finished loading: GET "http://127.0.0.1/laravel-u-editor-server/server?action=config&&noCache=1497493519719".

ueditor.config.js文件中的配置：  serverUrl: "/laravel-u-editor-server/server"

光有这个配置不行吧，在laravel中还得配置laravel-u-editor-server/server 的路由吧，要不找不到Cotroller啊

**Comment by st-titan** [comment]
已解决，是路由没加载进来。

**Comment by leekyy** [comment]
@st-titan 大哥 请问您是怎么解决的呀
