### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by dope2008** [stevenyangecho/laravel-u-editor#6]
请求后台配置项http错误，上传功能将不能正常使用！ 上传图片那里，是不是路由要自己写的？？

**Comment by stevenyangecho** [comment]
路由不需要自己写,得按照说明做完整配置

**Comment by dope2008** [comment]
配置是缓存问题，已经搞定了，现在的问题是，上传就返回can't find the uploaded file

**Comment by dope2008** [comment]
<img width="819" alt="91994079-6f64-4af8-b741-f2886ef9c4bd" src="https://cloud.githubusercontent.com/assets/4094083/9836007/0c695672-5a3a-11e5-87d5-c6bb2011c233.png">

**Comment by dope2008** [comment]
Undefined variable: UeditorLangFile (View: /Users/wangqinfeng/WWW/ad/resources/views/vendor/UEditor/head.blade.php) (View: /Users/wangqinfeng/WWW/ad/resources/views/vendor/UEditor/head.blade.php)

**Comment by dope2008** [comment]
找到问题了，修改public/laravel-u-editor/ueditor.config.js       // 服务器统一请求接口路径
        , serverUrl: "/laravel-u-editor/server/"    修改为  serverUrl: "/laravel-u-editor/server"   最后的/不要

**Comment by stevenyangecho** [comment]
最后面的 / 应该是没有影响才对,实际测试也没有影响.
建议多试几次,确实有影响就得改代码了

**Comment by vdion** [comment]
真是坑，public/laravel-u-editor/ueditor.config.js 需要把serverUrl修改下，作者真大意

**Comment by JellyBool** [comment]
@dope2008 我也是出现这个错误，你是怎么解决的？

`配置是缓存问题`这个是什么意思？我需要怎么配置？

**Comment by bunnkou** [comment]
@dope2008 “请求后台配置项http错误，上传功能将不能正常使用！” 
同求。。。

**Comment by bunnkou** [comment]
@JellyBool 兄弟，这个问题解决没?

**Comment by bunnkou** [comment]
UEditorServiceProvider 文件里
$router->any('/laravel-u-editor/server', 'Controller@server');
这里的 /laravel-u-editor/server 路由捕获不到，我换了个名字就可以了，但是我用 route:list 查了一下没有发现有相同的路由信息。
我是新手，请大神指教一下 @stevenyangecho

**Comment by xinz0526** [comment]
Laravel 5.1；Windows Xampp环境；laravel-u-editor 1.2依然出现“请求后台配置项http错误，上传功能将不能正常使用！” 
修改UEditorServiceProvider 和public/laravel-u-editor/ueditor.config.js路径依然不成功。求解

**Comment by stevenyangecho** [comment]
@bunnkou  @xinz0526  猜测原因应该是nginx apache的rewrite 没有配置正确.下个版本看争取把错误提示弄明显一点

**Comment by xinz0526** [comment]
好的，谢谢。

**Comment by EdenChan** [comment]
确实是
UEditorServiceProvider 文件里
$router->any('/laravel-u-editor/server', 'Controller@server');
路由匹配不上 但是把项目路径指定为根目录就正常了 这条路由非常奇怪。。

**Comment by bzs1984** [comment]
在5.2里面路由没有生效，通过route:list可以看到
UEditorServiceProvider 文件里
$router->any('/laravel-u-editor-server/server', 'Controller@server'); 配置的路由 但是不知为何访问会提示：
Controller method not found.

但是把这个路由单独写在 routes.php文件里面就可以访问了
Route::any('/laravel-u-editor-server/server', '\Stevenyangecho\UEditor\Controller@server');

这个地方一直没搞懂
