### ISSUE TITLE
更新到v1.4.3后，项目崩掉了

### ISSUE THREAD

**Issue by kairye** [stevenyangecho/laravel-u-editor#65]
PHP版本 7.1    Laravel 5.7
今天下午发布项目的时候，composer包更新到了1.4.3，然后整个项目都崩了
![image](https://user-images.githubusercontent.com/25899134/59923765-c689b780-9466-11e9-9091-c30e20bac24c.png)

**Comment by fmwww** [comment]
命名空间改了，修改项目中的命名空间或者回退到1.4.2，同时在composer.json中固定版本号

**Comment by kairye** [comment]
恩，就是在composer.json 固定版本号处理的。

**Comment by stevenyangecho** [comment]
已更新 1.4.4
