### ISSUE TITLE
找不到Provider

### ISSUE THREAD

**Issue by xiwang6428** [stevenyangecho/laravel-u-editor#69]
![image](https://user-images.githubusercontent.com/6893136/60149997-706f9800-9809-11e9-84f8-aef90d849dd1.png)

**Comment by xiwang6428** [comment]
UEditorServiceProvider变更了命名空间，导致无法正常使用。。。

**Comment by xiwang6428** [comment]
即使在app.config中改为引用：Shenglin\UEditor\UEditorServiceProvider::class,，也是如此。

**Comment by guanhui07** [comment]
我们这也遇到这问题
确实是命名空间被修改,最新的master主干 是合并过来的代码
所以我用https://github.com/shenglin-php/laravel-u-editor 这个fork 代码包  
然后app.php 配置 shenglin的 
```php
Shenglin\UEditor\UEditorServiceProvider::class,
```

暂时这么解决的

**Comment by stevenyangecho** [comment]
升级 最新版即可
