### ISSUE TITLE
后端配置项没有正常加载，上传插件不能正常使用！

### ISSUE THREAD

**Issue by JellyBool** [stevenyangecho/laravel-u-editor#7]
点开上传图片就出现：

`后端配置项没有正常加载，上传插件不能正常使用！`

环境：mac os , laravel 5.1

**Comment by JellyBool** [comment]
发现比较诡异，看了源码之后，感觉没啥问题，但是就是一直抱上面的错误。。。后来修改了一下路由就好了，好奇怪。。。

```
 $router->group($config, function ($router) {
            $router->any('/editor/server', 'Controller@server');
        });
```

然后配置，`public/laravel-u-editor/ueditor.config.js `对应的：

```
serverUrl: "/editor/server"
```

好诡异。。。

**Comment by stevenyangecho** [comment]
新版本已改...不知道为啥会有这个问题,我实际测试 linux 下面可以正常匹配路由的..
