### ISSUE TITLE
最近的更新很多BUG

### ISSUE THREAD

**Issue by fivenull** [stevenyangecho/laravel-u-editor#71]
1、composer下载更新后，发布会报类找不到，修改文件UEditorServiceProvider.php  命名空间才可以；
2、修改后，无法上传文件，返回后台配置错误

**Comment by stevenyangecho** [comment]
请确认 是否是 1.4.4 最新版

**Comment by fivenull** [comment]
是的，
"stevenyangecho/laravel-u-editor": "~1.4"

**Comment by fivenull** [comment]
![image](https://user-images.githubusercontent.com/49241070/60494454-6f46db00-9ce1-11e9-8261-9d302450e24e.png)
请看这个
